### ISSUE TITLE
Supporting netstandard2.0?

### ISSUE THREAD

**Issue by bstordrup** [fededim/Fededim.Extensions.Configuration.Protected#1]
I think it would be great to support `netstandard2.0`, which would make it available also for projects targeting `net462` and newer.

**Comment by fededim** [comment]
Yep, you are right, against all expectaton Data Protection api support both net462 and netstandard so I extended the Nuget package in the [new version](https://www.nuget.org/packages/Fededim.Extensions.Configuration.ProtectedJson). However I have just released an improved version of the package working on any ConfigurationSource check out this new package if interested [Fededim.Extensions.Configuration.Protected](https://www.nuget.org/packages/Fededim.Extensions.Configuration.Protected
), a new article on CodeProject on this new package will be published in the next few hours.
